### ISSUE TITLE
[BUG] Fonts are not loading

### ISSUE THREAD

**Issue by elia** [figpea/figpea-bug#1]
**Describe the bug**

Custom fonts (in my case Monserrat) are not loading

**To Reproduce**
1. Upload an XD design using custom fonts

**Expected behavior**
If the font is available on the system it should be used

**Screenshots**
<img width="100" alt="image" src="https://user-images.githubusercontent.com/1051/173691522-269f0d8f-2bac-4074-9c1f-c7c750272f3a.png">

_using times new roman instead_

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser with Version: Safari 15.5
 - Figpea Version: online version

**Comment by Keyang** [comment]
Thanks.
This bug has been fixed in v3.6.3.
